#!/usr/bin/env bash
# Regenerate docs/CODE.md: every source file in the repo, in one Markdown page,
# with a table of contents and line counts - the easiest thing to hand someone
# who wants to read the whole bot without cloning it. Run after any code change:
#   dev/build-code-doc.sh && git add docs/CODE.md
set -euo pipefail
cd "$(dirname "$0")/.."
out=docs/CODE.md

# Order: entry points, then the application package, then scripts, then tests.
files=$( { ls main.py train.py tune.py; ls src/*.py | grep -v __init__; ls dev/*.sh install.sh configure.sh proxmox/*; ls tests/*.py; } 2>/dev/null )

lang() { case "$1" in *.py) echo python;; *.sh) echo bash;; *) echo text;; esac; }
anchor() { echo "$1" | tr '/.' '--' | tr '[:upper:]' '[:lower:]'; }

{
  echo "# hugheylab-trading-bot — all the code in one page"
  echo
  echo "Generated by \`dev/build-code-doc.sh\` from commit \`$(git rev-parse --short HEAD)\` on $(date +%Y-%m-%d)."
  echo "Every source file, verbatim. Read top to bottom or jump from the table."
  echo
  echo "| File | Lines | What it is |"
  echo "|---|---:|---|"
  for f in $files; do
    n=$(wc -l < "$f")
    # First docstring/comment line as the one-line description.
    desc=$(awk 'NR<=8 { l=$0; sub(/^#!.*/, "", l); sub(/^"""/, "", l); sub(/^# ?/, "", l);
                       if (l ~ /^[[:space:]]*$/ || l ~ /^\[Unit\]/) next; print l; exit }' "$f" | cut -c1-90)
    echo "| [\`$f\`](#$(anchor "$f")) | $n | $desc |"
  done
  echo
  for f in $files; do
    echo "---"
    echo
    echo "## $f"
    echo
    echo '```'"$(lang "$f")"
    cat "$f"
    echo '```'
    echo
  done
} > "$out"
echo "wrote $out: $(wc -l < "$out") lines, $(echo "$files" | wc -w) files"
